// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// dpoisbinom
Rcpp::NumericVector dpoisbinom(Rcpp::IntegerVector& x, Rcpp::NumericVector& pp, bool log_d);
RcppExport SEXP poisbinom_dpoisbinom(SEXP xSEXP, SEXP ppSEXP, SEXP log_dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector& >::type pp(ppSEXP);
    Rcpp::traits::input_parameter< bool >::type log_d(log_dSEXP);
    rcpp_result_gen = Rcpp::wrap(dpoisbinom(x, pp, log_d));
    return rcpp_result_gen;
END_RCPP
}
// ppoisbinom
Rcpp::NumericVector ppoisbinom(Rcpp::IntegerVector& q, Rcpp::NumericVector& pp, bool lower_tail, bool log_p);
RcppExport SEXP poisbinom_ppoisbinom(SEXP qSEXP, SEXP ppSEXP, SEXP lower_tailSEXP, SEXP log_pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector& >::type q(qSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector& >::type pp(ppSEXP);
    Rcpp::traits::input_parameter< bool >::type lower_tail(lower_tailSEXP);
    Rcpp::traits::input_parameter< bool >::type log_p(log_pSEXP);
    rcpp_result_gen = Rcpp::wrap(ppoisbinom(q, pp, lower_tail, log_p));
    return rcpp_result_gen;
END_RCPP
}
// qpoisbinom
Rcpp::IntegerVector qpoisbinom(Rcpp::NumericVector& p, Rcpp::NumericVector& pp, bool lower_tail, bool log_p);
RcppExport SEXP poisbinom_qpoisbinom(SEXP pSEXP, SEXP ppSEXP, SEXP lower_tailSEXP, SEXP log_pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector& >::type p(pSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector& >::type pp(ppSEXP);
    Rcpp::traits::input_parameter< bool >::type lower_tail(lower_tailSEXP);
    Rcpp::traits::input_parameter< bool >::type log_p(log_pSEXP);
    rcpp_result_gen = Rcpp::wrap(qpoisbinom(p, pp, lower_tail, log_p));
    return rcpp_result_gen;
END_RCPP
}
// rpoisbinom
Rcpp::IntegerVector rpoisbinom(int n, Rcpp::NumericVector& pp);
RcppExport SEXP poisbinom_rpoisbinom(SEXP nSEXP, SEXP ppSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector& >::type pp(ppSEXP);
    rcpp_result_gen = Rcpp::wrap(rpoisbinom(n, pp));
    return rcpp_result_gen;
END_RCPP
}
