# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dpoisbinom <- function(x, pp, log_d = FALSE) {
    .Call('poisbinom_dpoisbinom', PACKAGE = 'poisbinom', x, pp, log_d)
}

ppoisbinom <- function(q, pp, lower_tail = TRUE, log_p = FALSE) {
    .Call('poisbinom_ppoisbinom', PACKAGE = 'poisbinom', q, pp, lower_tail, log_p)
}

qpoisbinom <- function(p, pp, lower_tail = TRUE, log_p = FALSE) {
    .Call('poisbinom_qpoisbinom', PACKAGE = 'poisbinom', p, pp, lower_tail, log_p)
}

rpoisbinom <- function(n, pp) {
    .Call('poisbinom_rpoisbinom', PACKAGE = 'poisbinom', n, pp)
}

